CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(100) NOT NULL,
    Lastname VARCHAR(100) NOT NULL,
    Birthday DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Tasca (
    Codi INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom VARCHAR(100) NOT NULL,
    Descripcio VARCHAR(100) NOT NULL,
    Responsable VARCHAR(100) NOT NULL,
    Colors VARCHAR(100) NOT NULL,
    Data_Inici DATETIME NOT NULL,
    Data_Final DATETIME NOT NULL
);